version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - run:
          name: Restore package dependencies
          command: |
            dotnet restore
      - run:
          name: Build release
          command: |
            dotnet publish -c Release -o bin/win --self-contained -r win-x64
            dotnet publish -c Release -o bin/linux --self-contained -r linux-x64
            dotnet publish -c Release -o bin/mac --self-contained -r osx-x64
      - store_artifacts:
          path: bin